# Generated by curation_concerns:models:install
class Collection < ActiveFedora::Base
  include ::CurationConcerns::CollectionBehavior

  property :short_description, predicate: ::RDF::DC.description, multiple: false
end
